"""Normalize database

Revision ID: 055c01eadf7e
Revises: 0005
Create Date: 2026-08-16 15:53:30.968756
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '055c01eadf7e'
down_revision: Union[str, None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('field_provider_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('field_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=40), nullable=False),
    sa.Column('external_id', sa.String(length=160), nullable=True),
    sa.Column('sync_status', sa.String(length=24), nullable=False),
    sa.Column('sync_error', sa.String(length=500), nullable=True),
    sa.Column('retryable', sa.Boolean(), nullable=False),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('field_id', 'provider', name='uq_field_provider_link')
    )
    op.create_index(op.f('ix_field_provider_links_external_id'), 'field_provider_links', ['external_id'], unique=False)
    op.create_index(op.f('ix_field_provider_links_field_id'), 'field_provider_links', ['field_id'], unique=False)
    op.alter_column('ai_chat_messages', 'thread_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_ai_chat_messages_field_id'), table_name='ai_chat_messages')
    op.drop_constraint(op.f('uq_chat_message_field_idempotency'), 'ai_chat_messages', type_='unique')
    op.drop_constraint(op.f('ai_chat_messages_field_id_fkey'), 'ai_chat_messages', type_='foreignkey')
    op.drop_column('ai_chat_messages', 'field_id')
    op.drop_index(op.f('ix_chat_attachments_field_id'), table_name='chat_attachments')
    op.drop_constraint(op.f('chat_attachments_field_id_fkey'), 'chat_attachments', type_='foreignkey')
    op.drop_column('chat_attachments', 'field_id')
    op.drop_column('field_recommendations', 'evidence')
    op.drop_column('fields', 'agro_error')
    op.drop_column('fields', 'last_satellite_sync')
    op.drop_column('fields', 'agro_status')
    op.drop_column('fields', 'agro_retryable')
    op.drop_column('fields', 'agromonitory_poly_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fields', sa.Column('agromonitory_poly_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.add_column('fields', sa.Column('agro_retryable', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('fields', sa.Column('agro_status', sa.VARCHAR(length=24), autoincrement=False, nullable=False))
    op.add_column('fields', sa.Column('last_satellite_sync', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('fields', sa.Column('agro_error', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('field_recommendations', sa.Column('evidence', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('chat_attachments', sa.Column('field_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('chat_attachments_field_id_fkey'), 'chat_attachments', 'fields', ['field_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_chat_attachments_field_id'), 'chat_attachments', ['field_id'], unique=False)
    op.add_column('ai_chat_messages', sa.Column('field_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('ai_chat_messages_field_id_fkey'), 'ai_chat_messages', 'fields', ['field_id'], ['id'], ondelete='CASCADE')
    op.create_unique_constraint(op.f('uq_chat_message_field_idempotency'), 'ai_chat_messages', ['field_id', 'idempotency_key'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_ai_chat_messages_field_id'), 'ai_chat_messages', ['field_id'], unique=False)
    op.alter_column('ai_chat_messages', 'thread_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_index(op.f('ix_field_provider_links_field_id'), table_name='field_provider_links')
    op.drop_index(op.f('ix_field_provider_links_external_id'), table_name='field_provider_links')
    op.drop_table('field_provider_links')
    # ### end Alembic commands ###
