"""Add UserNotification

Revision ID: 3f6d724aa284
Revises: c8e2a5f14d9b
Create Date: 2026-09-02 01:18:54.924408
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '3f6d724aa284'
down_revision: Union[str, None] = 'c8e2a5f14d9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('reference_id', sa.String(length=100), nullable=True),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_notifications_user_id'), 'user_notifications', ['user_id'], unique=False)
    op.drop_index('sensor_readings_time_idx', table_name='sensor_readings')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('sensor_readings_time_idx', 'sensor_readings', [sa.text('time DESC')], unique=False)
    op.drop_index(op.f('ix_user_notifications_user_id'), table_name='user_notifications')
    op.drop_table('user_notifications')
    # ### end Alembic commands ###
