"""add_user_roles_and_invitations

Revision ID: 42a5c0f83a43
Revises: 055c01eadf7e
Create Date: 2026-08-18 06:54:29.598484
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '42a5c0f83a43'
down_revision: Union[str, None] = '055c01eadf7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('role', sa.Enum('admin', 'agronomist', 'farm_manager', 'technician', 'mobile_user', name='userrole'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('invited_by_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['invited_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitations_email'), 'invitations', ['email'], unique=False)
    op.create_index(op.f('ix_invitations_status'), 'invitations', ['status'], unique=False)
    # Removed incorrect index drops for TimescaleDB hypertables
    op.add_column('users', sa.Column('role', sa.Enum('admin', 'agronomist', 'farm_manager', 'technician', 'mobile_user', name='userrole'), nullable=False, server_default='mobile_user'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    # Removed incorrect index recreations for TimescaleDB hypertables
    op.drop_index(op.f('ix_invitations_status'), table_name='invitations')
    op.drop_index(op.f('ix_invitations_email'), table_name='invitations')
    op.drop_table('invitations')
    # ### end Alembic commands ###
