[common]
platform = espressif32
board = esp32-s3-devkitc-1-n16r8
framework = arduino
monitor_speed = 115200

[env:esp32s3_n16r8_AgriVision]
extends = common
build_flags = 
    -D ARDUINO_USB_CDC_ON_BOOT=0
    -D BOARD_HAS_PSRAM
monitor_port = /dev/cu.usbserial-A5069RR4
lib_deps = 
    adafruit/Adafruit NeoPixel @ ^1.12.0
    paulstoffregen/OneWire @ ^2.3.8
    milesburton/DallasTemperature @ ^3.9.1
    bblanchon/ArduinoJson @ ^7.0.4

[env:esp32s3_n16r8_AgriVision-prod]
extends = common
build_flags = 
    -D ARDUINO_USB_CDC_ON_BOOT=0
    -D BOARD_HAS_PSRAM
    -D PROD_MODE
lib_deps = 
    adafruit/Adafruit NeoPixel @ ^1.12.0
    paulstoffregen/OneWire @ ^2.3.8
    milesburton/DallasTemperature @ ^3.9.1
    bblanchon/ArduinoJson @ ^7.0.4
    knolleary/PubSubClient @ ^2.8
monitor_port = /dev/cu.usbserial-A5069RR4
