[env:esp32s3_n16r8_AgriVision]
platform = espressif32
board = esp32-s3-devkitc-1-n16r8
framework = arduino

; Board hardware defaults are defined in boards/esp32-s3-devkitc-1-n16r8.json

; Project-specific compile flags
build_flags = 
    -D ARDUINO_USB_CDC_ON_BOOT=0
    -D BOARD_HAS_PSRAM

; Monitor Settings
monitor_speed = 115200
monitor_port = /dev/cu.usbserial-A5069RR4 ; Optional, but saves time

lib_deps = 
    adafruit/Adafruit NeoPixel @ ^1.12.0
    paulstoffregen/OneWire @ ^2.3.8
    milesburton/DallasTemperature @ ^3.9.1
    knolleary/PubSubClient @ ^2.8
    bblanchon/ArduinoJson @ ^7.0.4