"""
Recommendations API Endpoints

Serves stored AI-generated agronomic recommendations to the iOS app.
Recommendations are generated by the background AI Advisor loop (every 4 hours)
and can also be triggered on-demand via the /refresh endpoint.
"""

from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from typing import List
from uuid import UUID

from app.database import get_db
from app.models.db_models import Field, FieldRecommendation, User
from app.schemas.pydantic_schemas import RecommendationResponse
from app.core.auth import get_current_user
from pydantic import BaseModel

router = APIRouter(prefix="/api/fields", tags=["AI Recommendations"])


@router.get("/{field_id}/recommendations/", response_model=List[RecommendationResponse])
def get_recommendations(
    field_id: UUID,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user),
    limit: int = 10
):
    """
    Get the latest AI-generated recommendations for a specific field.
    Returns the most recent analysis results, ordered by creation time.
    """
    # Verify field ownership
    field = db.query(Field).filter(
        Field.id == field_id,
        Field.owner_id == current_user.id
    ).first()

    if not field:
        raise HTTPException(status_code=404, detail="Field not found or access denied")

    recommendations = (
        db.query(FieldRecommendation)
        .filter(FieldRecommendation.field_id == field_id)
        .order_by(FieldRecommendation.created_at.desc())
        .limit(limit)
        .all()
    )

    return recommendations


class RecommendationFeedback(BaseModel):
    status: str


@router.put("/{field_id}/recommendations/{recommendation_id}/feedback")
def update_recommendation_feedback(
    field_id: UUID,
    recommendation_id: UUID,
    feedback: RecommendationFeedback,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Allow the farmer to provide feedback (e.g. 'implemented', 'ignored') on a recommendation.
    This creates a memory feedback loop for the autonomous AI.
    """
    field = db.query(Field).filter(
        Field.id == field_id,
        Field.owner_id == current_user.id
    ).first()

    if not field:
        raise HTTPException(status_code=404, detail="Field not found or access denied")

    rec = db.query(FieldRecommendation).filter(
        FieldRecommendation.id == recommendation_id,
        FieldRecommendation.field_id == field_id
    ).first()

    if not rec:
        raise HTTPException(status_code=404, detail="Recommendation not found")

    if feedback.status not in ["pending", "implemented", "ignored"]:
        raise HTTPException(status_code=400, detail="Invalid status value. Must be 'pending', 'implemented', or 'ignored'.")

    rec.status = feedback.status
    db.commit()
    db.refresh(rec)
    return {"id": rec.id, "status": rec.status, "message": "Feedback recorded."}


@router.post("/{field_id}/recommendations/refresh/", status_code=202)
async def trigger_recommendation_refresh(
    field_id: UUID,
    db: Session = Depends(get_db),
    current_user: User = Depends(get_current_user)
):
    """
    Trigger an immediate AI analysis for a specific field.
    This runs the full data aggregation and Gemini reasoning pipeline on-demand.
    The result is persisted and will appear in the next GET request.
    """
    from app.services.scheduler import run_ai_for_field
    
    field = db.query(Field).filter(
        Field.id == field_id,
        Field.owner_id == current_user.id
    ).first()

    if not field:
        raise HTTPException(status_code=404, detail="Field not found or access denied")

    if not field.agromonitory_poly_id:
        raise HTTPException(
            status_code=425,
            detail="Field is not yet registered with the Satellite service. Wait for the next sync cycle."
        )

    # Run the AI analysis asynchronously in the background
    import asyncio
    asyncio.create_task(run_ai_for_field(field, db))

    return {"status": "accepted", "message": "AI analysis queued. Results will be available shortly."}
